### ISSUE TITLE
argument

### ISSUE THREAD

**Issue by moaeddy** [0x9ef/golang-uacbypasser#1]
what is argument to use keep getting this continuously

[ERR] Payload --payload argument mismatching
  -list
        Provide to get list of all currently techniques implemented
  -method string
        Provide method of UAC bypass (default "fodhelper")
  -payload string

sample have used so far

main IFEO c:\users\user2\desktop\payload.exe

**Comment by 0x9ef** [comment]
Im updated main.go , this bug now fixed. Use: main.exe -payload C:\payload\payload.exe -method ifeo . IFEO require elevated privileges.

**Comment by moaeddy** [comment]
none of the UACbypass is working. have you tried them. tested in windows 10 build 17134.706

**Comment by 0x9ef** [comment]
Maybe some of persistence techniques not worked because thay vulnerabilities fixed, im not test any of persistence, im rewriting exactly the same of WinPwnage source code to Golang, but once (once time elevation) techniques all worked fine for me, tested in Windows 8, 8.1, 10. At the moment i dont have time for check it and fix it. You can commit to correct this issue with modified source code.
